### DISCUSSION TITLE
Function arguments using variable?

### DISCUSSION THREAD

**Discussion by eloycoto** [IBM/prompt-declaration-language#215] [Q&A]
When the LLM reply with multiple tools, the arguments can be different. In pdl, the `args` is a object that can be like this:
```
description: Eloy test
defs:
  get_current_stock:
    function:
      product_name: str
    return:
      "FN::get_current_stock:: '${product_name}'\n"
text:
  - def: simple_call
    call: get_current_stock
    args:
      product_name: "Simple call!"
```

The problem is when the arguments for the function need to be parsed/object from another output, that it's not possible to send the result object to the `callBlock.args` parameter, as example:

```
description: Eloy test
defs:
  get_current_stock:
    function:
      product_name: str
    return:
      "FN::get_current_stock:: '${product_name}'\n"
text:

  - def: object_example
    text: '{"product_name": "from_object"}'
    parser: json
    contribute: []

  - def: simple_call
    call: get_current_stock
    args:
      product_name: "Simple call!"

  - "${object_example}\n"

  - def: with_object_args
    call: get_current_stock
    args: ${object_example}
``` 

I can create a function like this:

```
 get_current_weather:
    function:
      args: str
    return: 
      defs: 
        arguments:
          text: ${ args }
          parser: json 
      if: ${ arguments.location == "Tokyo"}
      then: The temperature in Tokyo is 20 celsius.
```

But that has a problem, all arguments are a single string, and it's prone to errors, and hard to reuse it. 

Is there any way to pass the resulting object to the functionBlock.args? I do not think so

@vazirim @mandel If you can have a look, it'll be great :)
