### DISCUSSION TITLE
Idea: Jsonschema parser for functions?

### DISCUSSION THREAD

**Discussion by eloycoto** [IBM/prompt-declaration-language#216] [Q&A]
When working with functions in PDL, there is a small disadvantage: you need to declare the function twice to use it. Once for PDL consumption, and another time to attach it to the tools section in the LLM call.

I was thinking of adding a new parser that takes advantage of:

https://github.com/IBM/prompt-declaration-language/blob/ad048b854793b5d392c335c17daa37998fa9d228/src/pdl/pdl_schema_utils.py#L32-L76

This way, the PDL script could look like this:
```
description: test
defs:
  get_current_stock:
    function:
      product_name: str
    return:
      "FN::get_current_stock:: '${product_name}'\n"
text:
  - def: stock_fn_jsonschema
    parser: jsonschema
    return:
      "${get_current_stock}"
```

Here, you define the jsonschema, and tools can be defined in an array using a for loop with all available PDL functions. The PDL script will be easier to read and feel more natural.

A small change to the PDL schema is needed, such as adding descriptions for arguments and functions, so it might be more complicated than it initially seems due to changes in the schema.
