### DISCUSSION TITLE
Version 0.3.0

### DISCUSSION THREAD

**Discussion by mandel** [IBM/prompt-declaration-language#367] [Announcements]
## What's Changed
* Port pdl-live to react+patternfly+vite by @starpit in https://github.com/IBM/prompt-declaration-language/pull/253
* Embed PDL interpreter into react (tauri) app builds by @starpit in https://github.com/IBM/prompt-declaration-language/pull/350
* Remove BAM support by @mandel in https://github.com/IBM/prompt-declaration-language/pull/265
* Config options for model default parameters by @esnible in https://github.com/IBM/prompt-declaration-language/pull/266
* Add a `match` block by @mandel in https://github.com/IBM/prompt-declaration-language/pull/252
* Don't crash without log on keyboard exit by @esnible in https://github.com/IBM/prompt-declaration-language/pull/346
* lowered lower bound of litellm to 1.57.3 by @vazirim in https://github.com/IBM/prompt-declaration-language/pull/365

## New Contributors
* @starpit made their first contribution in https://github.com/IBM/prompt-declaration-language/pull/253

**Full Changelog**: https://github.com/IBM/prompt-declaration-language/compare/v0.2.0...v0.3.0

<hr /><em>This discussion was created from the release <a href='https://github.com/IBM/prompt-declaration-language/releases/tag/v0.3.0'>Version 0.3.0</a>.</em>

**Comment by creatorsagi** [comment]
i would like to use Gemini's multimodal understanding features.
What would be a way to pass a video URI to gemini? Would highly appreciate a pdl code block example. I've been trying many things and none of them seems to work. For example:
text:  # New text block for video analysis
  - model: vertex_ai/gemini-1.5-flash-002
    def: VIDEO_ANALYSIS
    input: |
      Describe this video: 
      What are the key events and objects in the video?
    parameters:
      temperature: 0.1
      max_tokens: 1024
      video_uri: gs://gemini-test-media/test_files/duolingo_business_model.mp4
      mime_type: video/mp4

**Reply by vazirim** [reply]
@creatorsagi Thanks for reporting this, we will have a look

**Comment by vazirim** [comment]
@creatorsagi What error are you getting with the above code?

**Comment by vazirim** [comment]
@creatorsagi Sorry for the delay in the response. Here's how you would write this:

```
model: gemini/gemini-2.0-flash-001
input:
 data:
  - role: user
    content:
      - type: text
        text: "What are the key events and objects in the video?"
      - type: image_url
        image_url: 
          url: "https://storage.googleapis.com/gemini-test-media/test_files/duolingo_business_model.mp4"
```

@mandel
