### ISSUE TITLE
Update Tutorial

### ISSUE THREAD

**Issue by vazirim** [IBM/prompt-declaration-language#48]
Add sections on the following:

- [x] data: raw
- [x] code: use of variables from the context without jinja syntax, check if anything else is missing (PDL_SESSION)
- [x] roles, explain how to change the template from the parameters (see example below)
- [x] text/lastOf/array/object
- [x] pdl CLI latest arguments (readme, readme pages)
- [x] sandboxing
- [x] message block
- [x] say that args of function calls are expressions not blocks
- [x] warning detection for blocks that don't contribute, add an explicit contribute to turn off warning

```
parameters:
  roles:
    user:
       pre_message: ""
       post_message: ""
```
