### ISSUE TITLE
examples/notebooks/pdl.ipynb fails with 'list' object has no attribute 'result'

### ISSUE THREAD

**Issue by esnible** [IBM/prompt-declaration-language#561]
**Describe the bug**
Our _examples/notebooks/pdl.ipynb_ example fails with 

```
What is the meaning of life?
'list' object has no attribute 'result'
```

on the first cell

**To Reproduce**

```
cd prompt-declaration-language
jupyter-lab
```

Browse to e.g. http://localhost:8888/lab/workspaces/auto-7/tree/examples/notebooks/pdl.ipynb

Execute the `pip install` cell (if needed), execute the `%load_ext pdl.pdl_notebook_ext` cell, then execute the cell

```
%%pdl --reset-context
description: Model call
text: 
- "What is the meaning of life?\n"
- model: replicate/ibm-granite/granite-8b-code-instruct-128k
  parameters:
    stop_sequences: "!"
    include_stop_sequence: true
```

**Expected behavior**
The Jupyter notebook should explain the meaning of life. 😊😊😊
(Or, it should output a Replicate error.)

**Additional context**
We should stop using `replicate` in the Jupyter notebook examples as well.
